### ISSUE TITLE
Call to undefined method Xmf\Request::hasVar()

### ISSUE THREAD

**Issue by walkero-gr** [XoopsModules25x/adslight#11]
I am trying this module and when a user tries to create an new ad I get the following error
 
Fatal error: Call to undefined method Xmf\Request::hasVar() in /var/www/html/modules/adslight/addlisting.php on line 61

The website uses Xoops 2.5.8.1 and the server currently runs on PHP 5.6. I am in a process to upgrade everything as much as I can so to update to PHP 7.3 later, but the above issue blocks me.
Can you please recommend a solution on that?

**Comment by mambax7** [comment]
You should first switch to XOOPS 2.5.10

**Comment by walkero-gr** [comment]
Thank you so much for your reply.
