### ISSUE TITLE
Adding ckeditor

### ISSUE THREAD

**Issue by cesagonchu** [XoopsModules25x/adslight#3]
Can you add ckeditor?

Code here:
http://www.frxoops.org/modules/newbb/viewtopic.php?post_id=238563#forumpost238563

For information: you can download ckeditor here:
http://www.frxoops.org/modules/newbb/viewtopic.php?post_id=238528#forumpost238528

**Comment by mambax7** [comment]
We have all the editors here: https://github.com/XoopsModules25x/xoopseditors/tree/master/htdocs/class/xoopseditor
He should fork it, update it,  and then create a Pull Request for it.
